apiVersion: v1
kind: Namespace
metadata:
  name: aikernel-infrastructure
  labels:
    name: aikernel-infrastructure
    purpose: infrastructure
    environment: production
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: aikernel-monitoring
  labels:
    name: aikernel-monitoring
    purpose: observability
    environment: production
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: aikernel-data
  labels:
    name: aikernel-data
    purpose: data-storage
    environment: production
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: aikernel
  labels:
    name: aikernel
    purpose: application
    environment: production
    istio-injection: enabled
