apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aikernel-data

resources:
  - neo4j-namespace.yaml
  - neo4j-configmap.yaml
  - neo4j-statefulset.yaml
  - neo4j-read-replicas.yaml
  - neo4j-pdb.yaml

commonLabels:
  app: neo4j
  component: graph-database
  part-of: aikernel

images:
  - name: neo4j
    newName: neo4j
    newTag: 5.15-enterprise
