apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aikernel

commonLabels:
  app.kubernetes.io/name: redis
  app.kubernetes.io/component: cache
  app.kubernetes.io/part-of: aikernel
  app.kubernetes.io/managed-by: kustomize

resources:
  - redis-configmap.yaml
  - redis-pdb.yaml
  - redis-statefulset.yaml
  - redis-monitoring.yaml
  - redis-networkpolicy.yaml

secretGenerator:
  - name: redis-password
    literals:
      - password=CHANGE_ME_IN_PRODUCTION

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: redis
    newName: redis
    newTag: 7.2-alpine
  - name: oliver006/redis_exporter
    newName: oliver006/redis_exporter
    newTag: v1.55.0-alpine
